import React, { useEffect, useMemo, useState } from 'react'
import { BarChart3, Plus, RefreshCw, Trash2, Pencil } from 'lucide-react'
import { Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { supabase } from '../lib/supabase'
import { getBatchQuotes, searchSecurities, STATIC_SECURITIES, type SecuritySuggestion } from '../services/marketData'

type Account={id:string;name:string;type:string;provider:string|null}
type Holding={id:string;account_id:string|null;symbol:string;company_name:string;quantity:number;average_cost:number;current_price:number;previous_close:number|null;currency:string;notes:string|null;last_price_updated_at:string|null;account?:Account|null}
type Snapshot={date_key:string;total_value:number;total_cost:number}
const fmt=(v:number,c='CAD')=>new Intl.NumberFormat(undefined,{style:'currency',currency:c==='USD'?'USD':'CAD'}).format(v)

export function InvestmentsView(){
const [accounts,setAccounts]=useState<Account[]>([]); const [holdings,setHoldings]=useState<Holding[]>([]); const [snapshots,setSnapshots]=useState<Snapshot[]>([]); const [open,setOpen]=useState(false); const [refreshing,setRefreshing]=useState(false); const [q,setQ]=useState(''); const [suggestions,setSuggestions]=useState<SecuritySuggestion[]>([]); const [selected,setSelected]=useState<SecuritySuggestion|null>(null); const [qty,setQty]=useState(''); const [avg,setAvg]=useState(''); const [acc,setAcc]=useState(''); const [notes,setNotes]=useState(''); const [addingAccount,setAddingAccount]=useState(false); const [accType,setAccType]=useState('TFSA'); const [accName,setAccName]=useState('');
const load=async()=>{const [{data:a},{data:h},{data:s}]=await Promise.all([supabase.from('investment_accounts').select('*').order('created_at'),supabase.from('investment_holdings').select('*').order('created_at'),supabase.from('investment_value_snapshots').select('*').order('date_key')]); setAccounts((a??[]) as Account[]); setHoldings((h??[]) as Holding[]); setSnapshots((s??[]) as Snapshot[])}
useEffect(()=>{void load()},[])
useEffect(()=>{void(searchSecurities(q).then(setSuggestions))},[q])
const derived=useMemo(()=>{const mapped=holdings.map((h)=>{const totalCost=h.quantity*h.average_cost;const mv=h.quantity*h.current_price;const gl=mv-totalCost;return {...h,totalCost,mv,gl,ret:totalCost>0?(gl/totalCost)*100:0,account:accounts.find((a)=>a.id===h.account_id)||null}}); const pv=mapped.reduce((a,b)=>a+b.mv,0); const tc=mapped.reduce((a,b)=>a+b.totalCost,0); const gl=pv-tc; return {mapped,pv,tc,gl,ret:tc>0?(gl/tc)*100:0}},[holdings,accounts])
const saveHolding=async()=>{if(!selected||!acc||Number(qty)<=0||Number(avg)<0)return; const payload={symbol:selected.symbol,company_name:selected.companyName,exchange:selected.exchange,quantity:Number(qty),average_cost:Number(avg),current_price:selected.fallbackPrice,currency:selected.currency,account_id:acc,notes}; const {error}=await supabase.from('investment_holdings').insert(payload); if(!error){window.dispatchEvent(new CustomEvent('budgetly:toast',{detail:{message:'Holding added.'}})); setOpen(false); setSelected(null);setQ('');setQty('');setAvg('');setAcc('');setNotes('');void load()}}
const saveAccount=async()=>{if(!accName.trim())return; const {data,error}=await supabase.from('investment_accounts').insert({name:accName.trim(),type:accType}).select('*').single(); if(!error&&data){setAccounts((c)=>[...c,data as Account]); setAcc((data as Account).id); setAddingAccount(false); setAccName(''); window.dispatchEvent(new CustomEvent('budgetly:toast',{detail:{message:'Account added.'}}))}}
const refresh=async()=>{setRefreshing(true); const res=await getBatchQuotes(holdings.map((h)=>h.symbol)); if(res.notConfigured){window.dispatchEvent(new CustomEvent('budgetly:toast',{detail:{message:'Price refresh is not configured yet.'}})); setRefreshing(false); return} if(res.rateLimited){window.dispatchEvent(new CustomEvent('budgetly:toast',{detail:{message:'Price refresh limit reached. Try again later.'}})); setRefreshing(false); return} const by=new Map(res.quotes.map((x)=>[x.symbol,x])); await Promise.all(holdings.map((h)=>{const q=by.get(h.symbol); if(!q) return Promise.resolve(); return supabase.from('investment_holdings').update({current_price:q.price,previous_close:q.previousClose,last_price_updated_at:q.timestamp}).eq('id',h.id)})); const today=new Date().toISOString().slice(0,10); const total=derived.pv; await supabase.from('investment_value_snapshots').upsert({date_key:today,total_value:total,total_cost:derived.tc,gain_loss:derived.gl,return_percent:derived.ret}); window.dispatchEvent(new CustomEvent('budgetly:toast',{detail:{message:res.failed.length?'Could not update all prices. Showing last saved prices.':'Prices updated.'}})); setRefreshing(false); void load()}
return <section className='card'><div className='row' style={{justifyContent:'space-between',alignItems:'flex-start'}}><div><h2>Investments</h2><div className='muted'>Track your holdings, accounts, and portfolio performance manually.</div></div><div className='row gap'><select className='input'><option>All Accounts</option></select><button className='btn' onClick={()=>void refresh()} disabled={refreshing}><RefreshCw size={16}/>{refreshing?'Refreshing...':'Refresh Prices'}</button><button className='btn' onClick={()=>setOpen(true)}><Plus size={16}/>Add Holding</button></div></div></section>}
